version: "3"
services:

  db:
    image: mariadb:10.3
    environment:
      MYSQL_DATABASE: catalog
      MYSQL_USER: catalog
      MYSQL_PASSWORD: change-me
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - mysql:/var/lib/mysql

  php:
    build: .
    environment:
      DATABASE_URL: mysql://catalog:change-me@db:3306/catalog
      MAILER_URL: "null://localhost"
      DB_HOST: db
      DB_USER: catalog
      DB_PASSWORD: change-me
    ports:
      - 80:80

volumes:
  mysql:
